export * from './Home';
export * from './Login';
export * from './SignUp';
export * from './Nlabs';
export * from './PrivateRoute';
export * from './NavBar';
export * from './footer';
export * from './MakePredictions';
export * from './result';